version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suadmin
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: user-registration-app
    ports:
      - "8085:8098"  # map container's port 8098 to host 8085
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: suadmin
